# Generated by Django 3.0.7 on 2020-06-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('btype', models.CharField(max_length=100)),
                ('tech', models.CharField(max_length=100)),
                ('bstatus', models.CharField(max_length=100)),
                ('approve', models.BooleanField(default=False)),
                ('bdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolutionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('bug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bugdata.BugList')),
            ],
        ),
    ]
