# Generated by Django 3.0.7 on 2020-06-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('frontend', models.CharField(max_length=100)),
                ('backend', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('pstatus', models.CharField(max_length=100)),
                ('pdescription', models.TextField()),
            ],
        ),
    ]
